[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_N8N_WEBHOOK_URL = "https://vizionnaireai.app.n8n.cloud/webhook-test/a9b964b5-c3cd-42e6-b47a-2952961acc83"
  NEXT_PUBLIC_SITE_URL = "https://vizionnaire.fr"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https://vizionnaire.app.n8n.cloud;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 