[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_N8N_WEBHOOK_URL = "https://vizionnaire.app.n8n.cloud/webhook/orison-chat"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 